library(tidyverse)
library(stats)
library(grDevices)
library(readr)
########## Non-linear model for daily data ##################
# Fitting parameters for model4 from Roby et al 2019
#Author: Dave Moore and Anastasia Makhnykina
##### Read in pulse and non-pulse data generated by CreateVariableDuration.R



years_sum_Pulse0 <- read.csv("data/years_sum_Pulse0_DM.csv", header = TRUE, na.strings = "NA")
years_sum_Pulse1<- read.csv("data/years_sum_Pulse1_DM.csv", header = TRUE, na.strings = "NA")
years_sum1<- read.csv("data/years_sum1_DM.csv", header = TRUE, na.strings = "NA")

years_sum_Pulse0$date <- as.Date(years_sum_Pulse0$date)
years_sum_Pulse1$date <- as.Date(years_sum_Pulse1$date)
years_sum1$date <- as.Date(years_sum1$date)


# CHECK COLUMN NAMES AND DATA TYPES
str(years_sum_Pulse0)
str(years_sum_Pulse1)
str(years_sum1)

# Remove rows with missing values
years_sum_Pulse0 <- na.omit(years_sum_Pulse0)

# Calculate Soil Moisture
SoilMoisture <- years_sum_Pulse0$meanSWC5/100

# Assign variables
meanSWC5_NP <- SoilMoisture
meanST5_NP <- years_sum_Pulse0$meanST5
meanGPP_NP <- years_sum_Pulse0$meanGPP
GPPmax_NP <- max(years_sum_Pulse0$meanGPP)

# Fit model
Param_model4_NP <- nls(meanRECO ~ Fref*((meanGPP_NP/GPPmax_NP +n)/1+n) *
                         (1-c4*(0.1-meanSWC5_NP)^2)*exp(b4*meanST5_NP), 
                       data = years_sum_Pulse0,
                       start = list(Fref=0.75, c4=56.54, b4=0.04, n=0.84),
                       control = nls.control(maxiter = 1000, minFactor = 0.01)
)
Summary_Model4_NP = summary(Param_model4_NP)


# 
# Formula: meanRECO ~ Fref * ((meanGPP_NP/GPPmax_NP + n)/1 + n) * (1 - c4 * 
#                                                                    (0.1 - meanSWC5_NP)^2) * exp(b4 * meanST5_NP)
# 
#Estimated Wed May 3rd 
# Parameters:
#   Estimate Std. Error t value Pr(>|t|)    
# Fref     0.021298  25.796  < 2e-16 ***
#   c4   14.410701   4.860611   2.965  0.00307 ** 
#   b4    0.034738   0.001528  22.737  < 2e-16 ***
#   n     0.131463   0.004753  27.661  < 2e-16 ***
#   

# NON_Pulse parameters
FrefNP = 0.549414 
SMoptNP =0.125 
c4NP = 14.410701   
b4NP =  0.034738
nNP=  0.131463


# Remove rows with missing values
years_sum_Pulse1 <- na.omit(years_sum_Pulse1)

SoilMoisture_P =years_sum_Pulse1$meanSWC5/100
meanSWC5_P = SoilMoisture_P
meanST5_P = years_sum_Pulse1$meanST5
meanGPP_P = years_sum_Pulse1$meanGPP
GPPmax_P = max(years_sum_Pulse1$meanGPP)

Param_model4_P <- nls(meanRECO ~ Fref*((meanGPP_P/GPPmax_P +n)/1+n) *(1-c4*(0.1-meanSWC5_P)^2)*exp(b4*meanST5_P), 
                       data = years_sum_Pulse1,
                       start = list(Fref=0.75,  c4=56.54, b4=0.04, n=0.84),
                       control = nls.control(maxiter = 1000, minFactor = 0.01)
)
Summary_Model4_P = summary(Param_model4_P)
# # 
# Parameters:
#   Estimate Std. Error t value Pr(>|t|)    
# Fref   0.616634   0.045269  13.621  < 2e-16 ***
#   c4   -10.431847   1.596214  -6.535 1.01e-10 ***
#   b4     0.044407   0.002129  20.862  < 2e-16 ***
#   n      0.243863   0.014703  16.586  < 2e-16 ***
# Pulse parameters
FrefP = 0.616634 
SMoptP =0.125 
c4P = -10.431847   
b4P =   0.044407
nP=  0.243863




complete.cases(years_sum1)

# Remove rows with missing values
years_sum1 <- na.omit(years_sum1)

# Setting up drivers for all time
All_meanSWC5 =years_sum1$meanSWC5/100
All_meanST5 = years_sum1$meanST5
All_meanGPP = years_sum1$meanGPP
All_GPPmax = max(years_sum1$meanGPP)

#run model for full time series based on non-pulse time parameters
ALL_model4_NP = FrefNP*((All_meanGPP/All_GPPmax +nNP)/1+nNP) *(1-c4NP*(SMoptNP-All_meanSWC5)^2)*exp(b4NP*All_meanST5)
#run model for full time series based on pulse time parameters
All_model4_P = FrefP*((All_meanGPP/All_GPPmax +nP)/1+nP) *(1-c4P*(SMoptP-All_meanSWC5)^2)*exp(b4P*All_meanST5)


# Plot the RECO time series
plot(years_sum1$date, years_sum1$meanRECO, type = "p", col = "blue", xlab = "Timestamp", ylab = "RECO", cex = 0.8)

# Add the model output time series to the plot
points(years_sum1$date, ALL_model4_NP, col = "red", pch = 16, cex = 0.4)
points(years_sum1$date, All_model4_P, col = "cyan", pch = 16, cex = 0.4, alpha=0.5)

# create the legend
legend(x = "topright",
       legend = c("Measured RECO", "Pulse Model", "Non-Pulse Model"),
       pch = c(1, 16, 16),
       col = c("blue", "cyan", "red"),
       lty = c(NA, 1, 1),
       bty = "n")

# Add another x-axis with the year
par(new=TRUE)
plot(years_sum1$date, years_sum1$meanRECO, type = "n", axes=FALSE, xlab="", ylab="")
axis(side=3)
mtext("Year",side=3,line=2)
axis(side=1, at = as.numeric(format(years_sum1$date, "%Y")), labels = format(years_sum1$date, "%Y"))




plot(years_sum1$meanRECO,ALL_model4_NP, type = "p", col = "red", xlab = "MEASURED RECO", ylab = "Non-pulse model RECO")
text(x = 1, y = 2.5, labels = "Over estimation")
text(x = 3, y = 0.5, labels = "Under estimation")
points( years_sum1$meanRECO,years_sum1$meanRECO,  type = "l", col = "red")

plot(years_sum1$meanRECO,All_model4_P,  type = "p", col = "cyan", xlab = "MEASURED RECO", ylab = "Pulse model RECO")
text(x = 1, y = 2.5, labels = "Over estimation")
text(x = 3, y = 0.5, labels = "Under estimation")
points( years_sum1$meanRECO,years_sum1$meanRECO,  type = "l", col = "cyan")



# Calulate the model residual and investigate whether residuals are higher during pulse times. 
Model_residual_NP = years_sum1$meanRECO-ALL_model4_NP
hist(Model_residual_NP, col = "red")

Model_residual_P = years_sum1$meanRECO - All_model4_P
hist(Model_residual_P, col = "cyan")


# calculate RMSE
rmse_NP <- sqrt(mean((ALL_model4_NP - years_sum1$meanRECO)^2))
rmse_P <- sqrt(mean((All_model4_P - years_sum1$meanRECO)^2))
# calculate MAPE
mape_NP <- mean(abs(ALL_model4_NP - years_sum1$meanRECO) / years_sum1$meanRECO) * 100
mape_P <- mean(abs(All_model4_P - years_sum1$meanRECO) / years_sum1$meanRECO) * 100
# calculate R-squared
r_squared_NP <- cor(ALL_model4_NP, years_sum1$meanRECO)^2
r_squared_P <- cor(All_model4_P, years_sum1$meanRECO)^2

Reco_NP = sum(ALL_model4_NP)
Reco_P = sum(All_model4_P)
Reco_obs = sum(years_sum1$meanRECO)


plot(ALL_model4_NP,All_model4_P, xlab = "Non-Pulse Model Reco", ylab = "Pulse Model Reco")


# Set the plot size and resolution
png("model_comparison.png", width = 800, height = 800, units = "px", res = 300)

# Create a blank plot with axis labels and limits
plot(ALL_model4_NP, All_model4_P, xlab = "Non-Pulse Model Reco", ylab = "Pulse Model Reco", 
     xlim = c(0, 5), ylim = c(0, 5), cex.lab = 1.5, cex.axis = 1.2)

# Add a 1:1 line to the plot
abline(a = 0, b = 1, lty = 2)

# Add points to the plot
points(ALL_model4_NP, All_model4_P, pch = 16, col = "black", cex = 1.2)



# Save the plot
dev.off()


##############Fit all years #########
all_year_P <- read.csv("data/USWPulse.csv")

all_year_NP <- read.csv("data/USWPulseN.csv")
all_year_NP <- all_year_NP[-c(26)]

all_time <- read.csv("data/Summary_eddy.csv")
all_time <- all_time[-c(26)]

#### Fit non-pulse model ##########
all_year_NP <- na.omit(all_year_NP)

SoilMoisture <- all_year_NP$meanSWC5/100

# Assign variables
meanSWC5_NP <- SoilMoisture
meanST5_NP <- all_year_NP$meanST5
meanGPP_NP <- all_year_NP$meanGPP
GPPmax_NP <- max(all_year_NP$meanGPP)

# Fit model
Param_model_NP <- nls(meanRECO ~ Fref*((meanGPP_NP/GPPmax_NP +n)/1+n) *
                         (1-c4*(0.1-meanSWC5_NP)^2)*exp(b4*meanST5_NP), 
                       data = all_year_NP,
                       start = list(Fref=0.75, c4=56.54, b4=0.04, n=0.84),
                       control = nls.control(maxiter = 1000, minFactor = 0.01)
)
Summary_Model_NP = summary(Param_model_NP)


#Parameters:
#Estimate Std. Error t value Pr(>|t|)    
#Fref 1.238616   0.046312  26.745   <2e-16 ***
#c4   6.231683   2.838189   2.196   0.0282 *  
#b4   0.035775   0.001352  26.463   <2e-16 ***
#n    0.057335   0.001889  30.358   <2e-16 ***

# NON_Pulse parameters
FrefNP = 1.238616
SMoptNP =0.125 
c4NP = 6.231683  
b4NP =  0.035775
nNP=  0.057335 


### Fit Pulse model##################
all_year_P <- na.omit(all_year_P)

SoilMoisture_P = all_year_P$meanSWC5/100
meanSWC5_P = SoilMoisture_P
meanST5_P = all_year_P$meanST5
meanGPP_P = all_year_P$meanGPP
GPPmax_P = max(all_year_P$meanGPP)

Param_model_P <- nls(meanRECO ~ Fref*((meanGPP_P/GPPmax_P +n)/1+n) *(1-c4*(0.1-meanSWC5_P)^2)*exp(b4*meanST5_P), 
                      data = all_year_P,
                      start = list(Fref=0.75,  c4=56.54, b4=0.04, n=0.84),
                      control = nls.control(maxiter = 1000, minFactor = 0.01)
)
Summary_Model_P = summary(Param_model_P)
# # 
#Parameters:
#Estimate Std. Error t value Pr(>|t|)    
#Fref  0.392190   0.039721   9.874  < 2e-16 ***
#c4   -8.202348   1.675466  -4.896 1.28e-06 ***
#b4    0.051465   0.002666  19.302  < 2e-16 ***
#n     0.422998   0.033533  12.614  < 2e-16 ***

# Pulse parameters
FrefP = 0.392190
SMoptP = 0.125 
c4P = -8.202348  
b4P =  0.051465
nP=  0.422998 


# Setting up drivers for all time
#complete.cases(all_time)

all_time <- na.omit(all_time)

All_meanSWC5 = all_time$meanSWC5/100
All_meanST5 = all_time$meanST5
All_meanGPP = all_time$meanGPP
All_GPPmax = max(all_time$meanGPP)

#run model for full time series based on non-pulse time parameters
ALL_model_NP = FrefNP*((All_meanGPP/All_GPPmax +nNP)/1+nNP) *(1-c4NP*(SMoptNP-All_meanSWC5)^2)*exp(b4NP*All_meanST5)
#run model for full time series based on pulse time parameters
All_model_P = FrefP*((All_meanGPP/All_GPPmax +nP)/1+nP) *(1-c4P*(SMoptP-All_meanSWC5)^2)*exp(b4P*All_meanST5)


# Plot the RECO time series

plot(all_time$date, all_time$meanRECO)
plot(all_time$date, all_time$meanRECO, type = "p", col = "blue", xlab = "Timestamp", ylab = "RECO", cex = 0.8)

# Add the model output time series to the plot
points(#all_time$date,  
       ALL_model_NP, col = "red", pch = 16, cex = 0.4)
points(#all_time$date, 
  All_model_P, col = "cyan", pch = 16, cex = 0.4, alpha=0.5)


all_time %>%
  ggplot(aes(x=date))+
  geom_point(aes(y=meanRECO), color = "blue")+
  geom_point(aes(y=ALL_model_NP), color="red")+
  geom_point(aes(y=All_model_P), color = "cyan")











