########## Non-linear model for daily data ##################
# Fitting parameters for model4 from Roby et al 2019

##### Read in pulse and non-pulse data generated by CreateVariableDuration.R

years_sum_Pulse0 <- read.csv("data/years_sum_Pulse0_DM.csv", header = TRUE, na.strings = "NaN")
years_sum_Pulse1<- read.csv("data/years_sum_Pulse1_DM.csv", header = TRUE, na.strings = "NaN")
years_sum1<- read.csv("data/years_sum1_DM.csv", header = TRUE, na.strings = "NaN")

# STARTING PARAMETERS

SMopt =0.125 #Note that we FIXED SMopt at the value used in Roby et al 2019


SoilMoisture =years_sum_Pulse0$meanSWC5/100
meanSWC5_NP = SoilMoisture
meanST5_NP = years_sum_Pulse0$meanST5
meanGPP_NP = years_sum_Pulse0$meanGPP
GPPmax_NP = max(years_sum_Pulse0$meanGPP)

Param_model4_NP <- nls(meanRECO ~ Fref*((meanGPP_NP/GPPmax_NP +n)/1+n) *(1-c4*(0.1-meanSWC5_NP)^2)*exp(b4*meanST5_NP), 
                    data = years_sum_Pulse0,
                    start = list(Fref=0.75,  c4=56.54, b4=0.04, n=0.84),
                    control = nls.control(maxiter = 1000, minFactor = 0.01)
)
Summary_Model4_NP = summary(Param_model4_NP)

# Formula: meanRECO ~ Fref * ((meanGPP_NP/GPPmax_NP + n)/1 + n) * (1 - c4 * 
#                                                                    (0.1 - meanSWC5_NP)^2) * exp(b4 * meanST5_NP)
# 
# Parameters:
#   Estimate Std. Error t value Pr(>|t|)    
# Fref  0.556847   0.032703  17.027   <2e-16 ***
#   c4   -0.176707   5.661176  -0.031    0.975    
# b4    0.030299   0.002087  14.515   <2e-16 ***
#   n     0.145719   0.007544  19.316   <2e-16 ***
#   ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Residual standard error: 0.1902 on 886 degrees of freedom
# 
# Number of iterations to convergence: 6 
# Achieved convergence tolerance: 3.229e-06

# NON_Pulse parameters
FrefNP = 0.556847 
SMoptNP =0.125 
c4NP = -0.176707   
b4NP =  0.030299
nNP=  0.145719





SoilMoisture_P =years_sum_Pulse1$meanSWC5/100
meanSWC5_P = SoilMoisture_P
meanST5_P = years_sum_Pulse1$meanST5
meanGPP_P = years_sum_Pulse1$meanGPP
GPPmax_P = max(years_sum_Pulse1$meanGPP)

Param_model4_P <- nls(meanRECO ~ Fref*((meanGPP_P/GPPmax_P +n)/1+n) *(1-c4*(0.1-meanSWC5_P)^2)*exp(b4*meanST5_P), 
                       data = years_sum_Pulse1,
                       start = list(Fref=0.75,  c4=56.54, b4=0.04, n=0.84),
                       control = nls.control(maxiter = 1000, minFactor = 0.01)
)
Summary_Model4_P = summary(Param_model4_P)
# 
# Parameters:
#   Estimate Std. Error t value Pr(>|t|)    
# Fref  0.907670   0.076816   11.82   <2e-16 ***
#   c4   -1.975783   1.647082   -1.20    0.231    
# b4    0.037579   0.002554   14.71   <2e-16 ***
#   n     0.176306   0.012290   14.35   <2e-16 ***
# Pulse parameters
FrefP = 0.907670 
SMoptP =0.125 
c4P = -1.975783   
b4P =   0.037579
nP=  0.176306





# Setting up drivers for all time
All_meanSWC5 =years_sum1$meanSWC5/100
All_meanST5 = years_sum1$meanST5
All_meanGPP = years_sum1$meanGPP
All_GPPmax = max(years_sum1$meanGPP)

#run model for full time series based on non-pulse time parameters
ALL_model4_NP = FrefNP*((All_meanGPP/All_GPPmax +nNP)/1+nNP) *(1-c4NP*(SMoptNP-All_meanSWC5)^2)*exp(b4NP*All_meanST5)
#run model for full time series based on pulse time parameters
All_model4_P = FrefP*((All_meanGPP/All_GPPmax +nP)/1+nP) *(1-c4P*(SMoptP-All_meanSWC5)^2)*exp(b4P*All_meanST5)


# Plot the RECO time series
plot(years_sum1$meanRECO, type = "p", col = "blue", xlab = "Timestamp", ylab = "RECO")
# Add the model output time series to the plot
lines( ALL_model4_NP, type = "l", col = "red")
lines( All_model4_P, type = "l", col = "cyan")
# create the legend
legend(x = "topright",
       legend = c("Measured RECO", "Pulse Model", "Non-Pulse Model"),
       pch = c(1, NA, NA),
       col = c("blue", "cyan", "red"),
       lty = c(NA, 1, 1),
       bty = "n")




plot(years_sum1$meanRECO,ALL_model4_NP, type = "p", col = "red", xlab = "MEASURED RECO", ylab = "Non-pulse model RECO")
text(x = 1, y = 2.5, labels = "Over estimation")
text(x = 3, y = 0.5, labels = "Under estimation")
points( years_sum1$meanRECO,years_sum1$meanRECO,  type = "l", col = "red")

plot(years_sum1$meanRECO,All_model4_P,  type = "p", col = "cyan", xlab = "MEASURED RECO", ylab = "Pulse model RECO")
text(x = 1, y = 2.5, labels = "Over estimation")
text(x = 3, y = 0.5, labels = "Under estimation")
points( years_sum1$meanRECO,years_sum1$meanRECO,  type = "l", col = "cyan")


# Calulate the model residual and investigate whether residuals are higher during pulse times. 
Model_residual = years_sum1$meanRECO-ALL_model4_NP
plot(years_sum1$meanSWC5,Model_residual, xlab = "SWC", ylab = "Model Error")
